
const tarotInterpretations = {
    "Blázen": "Blázen symbolizuje nové začátky, potenciál a svobodu.",
    "Mág": "Mág je karta síly vůle, tvořivosti a schopností.",
    "Velekněžka": "Velekněžka reprezentuje intuici, tajemství a duchovní poznání.",
    "Císařovna": "Císařovna symbolizuje plodnost, tvořivost a hojnost.",
    "Císař": "Císař značí autoritu, strukturu a stabilitu.",
    "Velekněz": "Velekněz odkazuje na tradice, učení a duchovní vedení.",
    "Zamilovaní": "Zamilovaní představují lásku, spojení a důležitá rozhodnutí.",
    "Vůz": "Vůz symbolizuje směr, kontrolu a vítězství.",
    "Síla": "Síla ukazuje na odvahu, vnitřní sílu a zvládnutí strachu.",
    "Poustevník": "Poustevník značí introspekci, hledání pravdy a samotu.",
    "Kolo štěstí": "Kolo štěstí představuje změnu, osud a cykly života.",
    "Spravedlnost": "Spravedlnost znamená pravdu, rovnováhu a důsledky činů.",
    "Viselec": "Viselec ukazuje na oběť, změnu perspektivy a čekání.",
    "Smrt": "Smrt značí konec, transformaci a nový začátek.",
    "Mírnost": "Mírnost odkazuje na rovnováhu, trpělivost a harmonii.",
    "Ďábel": "Ďábel představuje závislosti, strach a připoutanost.",
    "Věž": "Věž symbolizuje náhlé změny, kolaps a osvobození.",
    "Hvězda": "Hvězda ukazuje na naději, inspiraci a duchovní vedení.",
    "Měsíc": "Měsíc značí iluze, intuici a podvědomí.",
    "Slunce": "Slunce symbolizuje radost, úspěch a vitalitu.",
    "Soud": "Soud odkazuje na znovuzrození, rozhodnutí a obnovu.",
    "Svět": "Svět představuje dokončení, jednotu a úspěch.",
    "Eso pohárů": "Nové začátky v lásce, radost, emocionální naplnění.",
    "Dva II poháry": "Harmonické vztahy, láska, přátelství, propojení.",
    "Tři III poháry": "Oslava, přátelství, sdílení radosti.",
    "Čtyři IV poháry": "Apatie, nespokojenost, přehlížení příležitostí, potřeba se zamyslet.",
    "Pět V pohárů": "Smutek, ztráta, zklamání, zaměření na negativní aspekty.",
    "Šest VI pohárů": "Nostalgie, vzpomínky, radost z minulosti, harmonie.",
    "Sedm VII pohárů": "Iluze, příliš mnoho možností, zmatení, potřeba se rozhodnout.",
    "Osm VIII pohárů": "Odchod, opuštění toho, co již neslouží, hledání smyslu.",
    "Devět IX pohárů": "Splnění přání, spokojenost, radost, materiální i emocionální naplnění.",
    "Deset X pohárů": "Štěstí, rodinná harmonie, naplnění ve vztazích, dokonalá radost.",
    "Páže pohárů": "Nové začátky v lásce, kreativita, romantika, otevřenost emocím.",
    "Rytíř pohárů": "Romantika, nabídka lásky, hledání snů, něžnost.",
    "Královna pohárů": "Empatie, péče, intuice, emocionální moudrost.",
    "Král pohárů": "Rovnováha mezi emocemi a rozumem, laskavost, moudrost."
};
